[programs.localnet]
ico_platform = "4UJV9VxwoewYhw1qZKtPoVAdhd4tW8AaaDzpawuN9YuA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 20000 tests/ico-platform.js"
